In [4]:
import torch


In [5]:
x = torch.Tensor([5,3])
y = torch.Tensor([2,1])

In [6]:
print(x*y)

tensor([10.,  3.])


In [7]:
x = torch.zeros([2,5])

In [8]:
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [9]:
x.shape

torch.Size([2, 5])

In [10]:
y = torch.rand([2,5])

In [11]:
print(y)

tensor([[0.3761, 0.5984, 0.9706, 0.7255, 0.4743],
        [0.7602, 0.7219, 0.2300, 0.3453, 0.3075]])


In [12]:
y

tensor([[0.3761, 0.5984, 0.9706, 0.7255, 0.4743],
        [0.7602, 0.7219, 0.2300, 0.3453, 0.3075]])

In [13]:
y.view

<function Tensor.view>

In [15]:
z = y.view([1,10])

In [16]:
z


tensor([[0.3761, 0.5984, 0.9706, 0.7255, 0.4743, 0.7602, 0.7219, 0.2300, 0.3453,
         0.3075]])